// Standard opplæringsoppgaver for servicehandel (seedes per kjede via knapp).
export const STANDARD_OPPLAERING = [
  { kategori: 'Kasse', tittel: 'Logge på kassesystemet', beskrivelse: 'Bruk personlig pin/kort. Bytte mellom kasser hvis flere.', rekkefolge: 10, estimert_min: 10 },
  { kategori: 'Kasse', tittel: 'Bruke skannerkasse — vanlig salg', beskrivelse: 'Skanne varer, behandle rabatter, avslutte salg.', rekkefolge: 20, estimert_min: 30 },
  { kategori: 'Kasse', tittel: 'Behandle drivstoff-salg', beskrivelse: 'Knytte pumpenummer, betaling med ulike kort.', rekkefolge: 30, estimert_min: 20 },
  { kategori: 'Kasse', tittel: 'Returnere/refundere et salg', beskrivelse: 'Når kunden vil ha penger tilbake — håndtering.', rekkefolge: 40, estimert_min: 15 },
  { kategori: 'Kasse', tittel: 'Kontanter — start og slutt på dag', beskrivelse: 'Telle opp kasse, fylle veksel, bytte myntruller.', rekkefolge: 50, estimert_min: 30 },
  { kategori: 'Drivstoff', tittel: 'Stenge og åpne pumpe', beskrivelse: 'Når noe er feil eller pumpen må stoppes.', rekkefolge: 100, estimert_min: 15 },
  { kategori: 'Drivstoff', tittel: 'Beredskap ved drivstoffsøl', beskrivelse: 'Hva gjør vi hvis det renner over eller spruter.', rekkefolge: 110, estimert_min: 30 },
  { kategori: 'Drivstoff', tittel: 'Bytte rengjøringsmiddel for vindusvasker', beskrivelse: 'Påfylling og bytte ved tomt.', rekkefolge: 120, estimert_min: 10 },
  { kategori: 'Bake', tittel: 'Bake boller fra fryser', beskrivelse: 'Hvor lenge, hvilke temperaturer, hva skal i ovnen sammen.', rekkefolge: 200, estimert_min: 30 },
  { kategori: 'Bake', tittel: 'Lage kaffe og varme drikker', beskrivelse: 'Bønnekvern, espresso, kakao, te. Vask av maskiner.', rekkefolge: 210, estimert_min: 30 },
  { kategori: 'Bake', tittel: 'Lage pølser/wienere', beskrivelse: 'Forhåndsvarme, hold-tid, kasting når over tid.', rekkefolge: 220, estimert_min: 20 },
  { kategori: 'Bake', tittel: 'Lage panini/baguette/påsmurt', beskrivelse: 'Toaster, varme-tid, kombinasjoner.', rekkefolge: 230, estimert_min: 20 },
  { kategori: 'Renhold', tittel: 'Daglig renhold — innenfor', beskrivelse: 'Toaletter, lokale, vinduer, gulv.', rekkefolge: 300, estimert_min: 60 },
  { kategori: 'Renhold', tittel: 'Daglig renhold — utenfor', beskrivelse: 'Pumpene, søppel, kaffekrukker, asfalt.', rekkefolge: 310, estimert_min: 30 },
  { kategori: 'Renhold', tittel: 'Vask av kaffemaskin og softis', beskrivelse: 'Daglig vs ukentlig — protokoll.', rekkefolge: 320, estimert_min: 30 },
  { kategori: 'Sikkerhet', tittel: 'Brannrutiner — varsling og utgang', beskrivelse: 'Hvor er slukkeapparatene, hva gjør jeg.', rekkefolge: 400, estimert_min: 20 },
  { kategori: 'Sikkerhet', tittel: 'Ranerutiner', beskrivelse: 'Hvis noen truer eller er aggressiv — hvordan reagerer jeg.', rekkefolge: 410, estimert_min: 15 },
  { kategori: 'Sikkerhet', tittel: 'Aldersgrense — tobakk, snus, øl', beskrivelse: 'Når kreve legitimasjon, avvise salg.', rekkefolge: 420, estimert_min: 10 },
  { kategori: 'Drift', tittel: 'Påfylling av varer i hyller', beskrivelse: 'Fifo, holdbarhetssjekk, plassering.', rekkefolge: 500, estimert_min: 30 },
  { kategori: 'Drift', tittel: 'Registrere svinn', beskrivelse: 'Hva regnes som svinn, hvordan registreres det i appen.', rekkefolge: 510, estimert_min: 15 },
  { kategori: 'Service', tittel: 'Hjelpe kunde — generelt', beskrivelse: 'Hilse, lytte, foreslå, takke. Tonefall.', rekkefolge: 600, estimert_min: 20 },
]
