-- =====================================================================
-- 0017 - Avtalevokter (FJERNET 2026-08-18)
--
-- Denne migrasjonen lagde tabellen `fakturaer`, storage-boetta med samme
-- navn og RLS-policyene for dem. Funksjonen leste fakturaer med AI-vision
-- og bygde forbruksprofil per leverandor paa tvers av stasjoner.
--
-- Den ble aldri kjort mot produksjon - dekningssjekken i
-- rls_vakthund.sql avslorte 2026-08-18 at `fakturaer` ikke fantes i
-- basen, mens sida /avtalevokter fortsatt laa der og feilet stille.
--
-- Innholdet er toemt, ikke fila slettet. Migrasjonssettet kjores av og
-- til om igjen fra 0001, og da skal 0017 ikke gjenskape en tabell 0106
-- river rett etterpaa. Nummeret staar igjen saa rekkefolgen bak den ikke
-- flytter seg, og saa denne forklaringen har et sted aa bo.
--
-- Ryddingen i basen ligger i 0106_avtalevokter_bort.sql.
--
-- Prislinja `premium_avtalevokter` i retailers lever fortsatt. Den styrer
-- fakturering (api/faktura, cron/rapporter-bruk) og er en egen beslutning.
-- =====================================================================

-- Med vilje tom.
