-- ---------------------------------------------------------------------
-- 0093: rapporttyper som koden bruker, men enum-en ikke har
-- ---------------------------------------------------------------------
-- Opplasting av timesalg feilet med
--   invalid input value for enum rapporttype: "st1_salesperhour_inneute"
--
-- To verdier koden har brukt lenge finnes ikke i typen:
--
--   st1_salesperhour_inneute  0603-rapporten med inne-/utekunder. Enum-en
--                             har bare 'st1_salesperhour' (den gamle 0758).
--   salgsgrid_varetrans       synlig svinn. Enum-en har 'salesgrid_varetrans'
--                             - engelsk stavemaate, aldri brukt av koden.
--
-- Hvorfor det ikke ble oppdaget: koeveien (Storage + nattjobb) setter
-- rapporttype med en UPDATE hvis feil aldri ble sjekket, saa jobben gikk
-- videre og dataene landet - med rapporttype 'ukjent' i basen.
-- Nettleserveien setter den i INSERT, og der kastet det. Samme fil, to
-- veier, ett virket.
--
-- De gamle verdiene beholdes. Eksisterende rader kan referere dem, og en
-- enum-verdi kan ikke fjernes uten aa skrive om typen.
--
-- ---------------------------------------------------------------------
-- DENNE FILA MAA KJORES ALENE, FOR 0094.
-- ---------------------------------------------------------------------
-- Postgres nekter aa BRUKE en ny enum-verdi i samme transaksjon som den
-- ble lagt til:
--   55P04: unsafe use of new value ... New enum values must be committed
--   before they can be used.
-- SQL-editoren kjorer hele skriptet som en transaksjon, saa oppryddingen
-- som bruker verdien ligger i 0094. Slaa dem aldri sammen igjen.
alter type public.rapporttype add value if not exists 'st1_salesperhour_inneute';
alter type public.rapporttype add value if not exists 'salgsgrid_varetrans';
